### ISSUE TITLE
Colab Notebook appears blank

### ISSUE THREAD

**Issue by armarion** [guijinSON/NNHedge#1]
Is the link to the Colab Notebook working? It's pulling up a blank notebook

**Comment by guijinSON** [comment]
Hi @armarion , thanks for opening this issue!

I have just realized that the colab notebook returns a blank page. 
For the moment, I am trying to expand the repo and the working paper. So I will make sure I have it fixed by the end of my work.

**Comment by guijinSON** [comment]
Hi @armarion, if you are still in need of guidelines I added simple codes that might help you use my repo. 
I am slightly aware that they might not be enough and will try to add better annotations soon.
